<?php

namespace Database\Seeders;

use App\Models\Municipios;
use Illuminate\Database\Seeder;

class MunicipiosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Municipios::insert([
            ['cod_municipio' => '0101', 'cod_departamento' => '01', 'nombre_municipio' => 'La Ceiba'],
            ['cod_municipio' => '0102', 'cod_departamento' => '01', 'nombre_municipio' => 'El Porvenir'],
            ['cod_municipio' => '0103', 'cod_departamento' => '01', 'nombre_municipio' => 'Esparta'],
            ['cod_municipio' => '0104', 'cod_departamento' => '01', 'nombre_municipio' => 'Jutiapa'],
            ['cod_municipio' => '0105', 'cod_departamento' => '01', 'nombre_municipio' => 'La Masica'],
            ['cod_municipio' => '0106', 'cod_departamento' => '01', 'nombre_municipio' => 'San Francisco'],
            ['cod_municipio' => '0107', 'cod_departamento' => '01', 'nombre_municipio' => 'Tela'],
            ['cod_municipio' => '0108', 'cod_departamento' => '01', 'nombre_municipio' => 'Arizona'],
            ['cod_municipio' => '0201', 'cod_departamento' => '02', 'nombre_municipio' => 'Trujillo'],
            ['cod_municipio' => '0202', 'cod_departamento' => '02', 'nombre_municipio' => 'Balfate'],
            ['cod_municipio' => '0203', 'cod_departamento' => '02', 'nombre_municipio' => 'Iriona'],
            ['cod_municipio' => '0204', 'cod_departamento' => '02', 'nombre_municipio' => 'Limon'],
            ['cod_municipio' => '0205', 'cod_departamento' => '02', 'nombre_municipio' => 'Saba'],
            ['cod_municipio' => '0206', 'cod_departamento' => '02', 'nombre_municipio' => 'Santa Fe'],
            ['cod_municipio' => '0207', 'cod_departamento' => '02', 'nombre_municipio' => 'Santa Rosa de Aguan'],
            ['cod_municipio' => '0208', 'cod_departamento' => '02', 'nombre_municipio' => 'Sonaguera'],
            ['cod_municipio' => '0209', 'cod_departamento' => '02', 'nombre_municipio' => 'Tocoa'],
            ['cod_municipio' => '0210', 'cod_departamento' => '02', 'nombre_municipio' => 'Bonito Oriental'],
            ['cod_municipio' => '0301', 'cod_departamento' => '03', 'nombre_municipio' => 'Comayagua'],
            ['cod_municipio' => '0302', 'cod_departamento' => '03', 'nombre_municipio' => 'Ajuterique'],
            ['cod_municipio' => '0303', 'cod_departamento' => '03', 'nombre_municipio' => 'El Rosario'],
            ['cod_municipio' => '0304', 'cod_departamento' => '03', 'nombre_municipio' => 'Esquias'],
            ['cod_municipio' => '0305', 'cod_departamento' => '03', 'nombre_municipio' => 'Humuya'],
            ['cod_municipio' => '0306', 'cod_departamento' => '03', 'nombre_municipio' => 'La Libertad'],
            ['cod_municipio' => '0307', 'cod_departamento' => '03', 'nombre_municipio' => 'Lamani'],
            ['cod_municipio' => '0308', 'cod_departamento' => '03', 'nombre_municipio' => 'La Trinidad'],
            ['cod_municipio' => '0309', 'cod_departamento' => '03', 'nombre_municipio' => 'Lejamani'],
            ['cod_municipio' => '0310', 'cod_departamento' => '03', 'nombre_municipio' => 'Meambar'],
            ['cod_municipio' => '0311', 'cod_departamento' => '03', 'nombre_municipio' => 'Minas de Oro'],
            ['cod_municipio' => '0312', 'cod_departamento' => '03', 'nombre_municipio' => 'Ojos de Agua'],
            ['cod_municipio' => '0313', 'cod_departamento' => '03', 'nombre_municipio' => 'San Jeronimo'],
            ['cod_municipio' => '0314', 'cod_departamento' => '03', 'nombre_municipio' => 'San Jose de Comayagua'],
            ['cod_municipio' => '0315', 'cod_departamento' => '03', 'nombre_municipio' => 'San Jose del Potrero'],
            ['cod_municipio' => '0316', 'cod_departamento' => '03', 'nombre_municipio' => 'San Luis'],
            ['cod_municipio' => '0317', 'cod_departamento' => '03', 'nombre_municipio' => 'San Sebastian'],
            ['cod_municipio' => '0318', 'cod_departamento' => '03', 'nombre_municipio' => 'Siguatepeque'],
            ['cod_municipio' => '0319', 'cod_departamento' => '03', 'nombre_municipio' => 'Villa de San Antonio'],
            ['cod_municipio' => '0320', 'cod_departamento' => '03', 'nombre_municipio' => 'Las Lajas'],
            ['cod_municipio' => '0321', 'cod_departamento' => '03', 'nombre_municipio' => 'Taulabe'],
            ['cod_municipio' => '0401', 'cod_departamento' => '04', 'nombre_municipio' => 'Santa Rosa de Copan'],
            ['cod_municipio' => '0402', 'cod_departamento' => '04', 'nombre_municipio' => 'Cabana'],
            ['cod_municipio' => '0403', 'cod_departamento' => '04', 'nombre_municipio' => 'Concepcion'],
            ['cod_municipio' => '0404', 'cod_departamento' => '04', 'nombre_municipio' => 'Copan Ruinas'],
            ['cod_municipio' => '0405', 'cod_departamento' => '04', 'nombre_municipio' => 'Corquin'],
            ['cod_municipio' => '0406', 'cod_departamento' => '04', 'nombre_municipio' => 'Cucuyagua'],
            ['cod_municipio' => '0407', 'cod_departamento' => '04', 'nombre_municipio' => 'Dolores'],
            ['cod_municipio' => '0408', 'cod_departamento' => '04', 'nombre_municipio' => 'Dulce Nombre'],
            ['cod_municipio' => '0409', 'cod_departamento' => '04', 'nombre_municipio' => 'El Paraiso'],
            ['cod_municipio' => '0410', 'cod_departamento' => '04', 'nombre_municipio' => 'Florida'],
            ['cod_municipio' => '0411', 'cod_departamento' => '04', 'nombre_municipio' => 'La Jigua'],
            ['cod_municipio' => '0412', 'cod_departamento' => '04', 'nombre_municipio' => 'La Union'],
            ['cod_municipio' => '0413', 'cod_departamento' => '04', 'nombre_municipio' => 'Nueva Arcadia'],
            ['cod_municipio' => '0414', 'cod_departamento' => '04', 'nombre_municipio' => 'San Agustin'],
            ['cod_municipio' => '0415', 'cod_departamento' => '04', 'nombre_municipio' => 'San Antonio'],
            ['cod_municipio' => '0416', 'cod_departamento' => '04', 'nombre_municipio' => 'San Jeronimo'],
            ['cod_municipio' => '0417', 'cod_departamento' => '04', 'nombre_municipio' => 'San Jose'],
            ['cod_municipio' => '0418', 'cod_departamento' => '04', 'nombre_municipio' => 'San Juan de Opoa'],
            ['cod_municipio' => '0419', 'cod_departamento' => '04', 'nombre_municipio' => 'San Nicolas'],
            ['cod_municipio' => '0420', 'cod_departamento' => '04', 'nombre_municipio' => 'San Pedro'],
            ['cod_municipio' => '0421', 'cod_departamento' => '04', 'nombre_municipio' => 'Santa Rita'],
            ['cod_municipio' => '0422', 'cod_departamento' => '04', 'nombre_municipio' => 'Trinidad de Copan'],
            ['cod_municipio' => '0423', 'cod_departamento' => '04', 'nombre_municipio' => 'Veracruz'],
            ['cod_municipio' => '0501', 'cod_departamento' => '05', 'nombre_municipio' => 'San Pedro Sula'],
            ['cod_municipio' => '0502', 'cod_departamento' => '05', 'nombre_municipio' => 'Choloma'],
            ['cod_municipio' => '0503', 'cod_departamento' => '05', 'nombre_municipio' => 'Omoa'],
            ['cod_municipio' => '0504', 'cod_departamento' => '05', 'nombre_municipio' => 'Pimienta'],
            ['cod_municipio' => '0505', 'cod_departamento' => '05', 'nombre_municipio' => 'Potrerillos'],
            ['cod_municipio' => '0506', 'cod_departamento' => '05', 'nombre_municipio' => 'Puerto Cortes'],
            ['cod_municipio' => '0507', 'cod_departamento' => '05', 'nombre_municipio' => 'San Antonio de Cortes'],
            ['cod_municipio' => '0508', 'cod_departamento' => '05', 'nombre_municipio' => 'San Francisco de Yojoa'],
            ['cod_municipio' => '0509', 'cod_departamento' => '05', 'nombre_municipio' => 'San Manuel'],
            ['cod_municipio' => '0510', 'cod_departamento' => '05', 'nombre_municipio' => 'Santa Cruz de Yojoa'],
            ['cod_municipio' => '0511', 'cod_departamento' => '05', 'nombre_municipio' => 'Villanueva'],
            ['cod_municipio' => '0512', 'cod_departamento' => '05', 'nombre_municipio' => 'La Lima'],
            ['cod_municipio' => '0601', 'cod_departamento' => '06', 'nombre_municipio' => 'Choluteca'],
            ['cod_municipio' => '0602', 'cod_departamento' => '06', 'nombre_municipio' => 'Apacilagua'],
            ['cod_municipio' => '0603', 'cod_departamento' => '06', 'nombre_municipio' => 'Concepcion de Maria'],
            ['cod_municipio' => '0604', 'cod_departamento' => '06', 'nombre_municipio' => 'Duyure'],
            ['cod_municipio' => '0605', 'cod_departamento' => '06', 'nombre_municipio' => 'El Corpus'],
            ['cod_municipio' => '0606', 'cod_departamento' => '06', 'nombre_municipio' => 'El Triunfo'],
            ['cod_municipio' => '0607', 'cod_departamento' => '06', 'nombre_municipio' => 'Marcovia'],
            ['cod_municipio' => '0608', 'cod_departamento' => '06', 'nombre_municipio' => 'Morolica'],
            ['cod_municipio' => '0609', 'cod_departamento' => '06', 'nombre_municipio' => 'Namasigue'],
            ['cod_municipio' => '0610', 'cod_departamento' => '06', 'nombre_municipio' => 'Orocuina'],
            ['cod_municipio' => '0611', 'cod_departamento' => '06', 'nombre_municipio' => 'Pespire'],
            ['cod_municipio' => '0612', 'cod_departamento' => '06', 'nombre_municipio' => 'San Antonio de Flores'],
            ['cod_municipio' => '0613', 'cod_departamento' => '06', 'nombre_municipio' => 'San Isidro'],
            ['cod_municipio' => '0614', 'cod_departamento' => '06', 'nombre_municipio' => 'San Jose'],
            ['cod_municipio' => '0615', 'cod_departamento' => '06', 'nombre_municipio' => 'San Marcos de Colon'],
            ['cod_municipio' => '0616', 'cod_departamento' => '06', 'nombre_municipio' => 'Santa Ana de Yusguare'],
            ['cod_municipio' => '0701', 'cod_departamento' => '07', 'nombre_municipio' => 'Yuscaran'],
            ['cod_municipio' => '0702', 'cod_departamento' => '07', 'nombre_municipio' => 'Alauca'],
            ['cod_municipio' => '0703', 'cod_departamento' => '07', 'nombre_municipio' => 'Danli'],
            ['cod_municipio' => '0704', 'cod_departamento' => '07', 'nombre_municipio' => 'El Paraiso'],
            ['cod_municipio' => '0705', 'cod_departamento' => '07', 'nombre_municipio' => 'Guinope'],
            ['cod_municipio' => '0706', 'cod_departamento' => '07', 'nombre_municipio' => 'Jacaleapa'],
            ['cod_municipio' => '0707', 'cod_departamento' => '07', 'nombre_municipio' => 'Liure'],
            ['cod_municipio' => '0708', 'cod_departamento' => '07', 'nombre_municipio' => 'Moroceli'],
            ['cod_municipio' => '0709', 'cod_departamento' => '07', 'nombre_municipio' => 'Oropoli'],
            ['cod_municipio' => '0710', 'cod_departamento' => '07', 'nombre_municipio' => 'Potrerillos'],
            ['cod_municipio' => '0711', 'cod_departamento' => '07', 'nombre_municipio' => 'San Antonio de Flores'],
            ['cod_municipio' => '0712', 'cod_departamento' => '07', 'nombre_municipio' => 'San Lucas'],
            ['cod_municipio' => '0713', 'cod_departamento' => '07', 'nombre_municipio' => 'San Matias'],
            ['cod_municipio' => '0714', 'cod_departamento' => '07', 'nombre_municipio' => 'Soledad'],
            ['cod_municipio' => '0715', 'cod_departamento' => '07', 'nombre_municipio' => 'Teupasenti'],
            ['cod_municipio' => '0716', 'cod_departamento' => '07', 'nombre_municipio' => 'Texiguat'],
            ['cod_municipio' => '0717', 'cod_departamento' => '07', 'nombre_municipio' => 'Vado Ancho'],
            ['cod_municipio' => '0718', 'cod_departamento' => '07', 'nombre_municipio' => 'Yauyupe'],
            ['cod_municipio' => '0719', 'cod_departamento' => '07', 'nombre_municipio' => 'Trojes'],
            ['cod_municipio' => '0801', 'cod_departamento' => '08', 'nombre_municipio' => 'Distrito Central'],
            ['cod_municipio' => '0802', 'cod_departamento' => '08', 'nombre_municipio' => 'Alubaren'],
            ['cod_municipio' => '0803', 'cod_departamento' => '08', 'nombre_municipio' => 'Cedros'],
            ['cod_municipio' => '0804', 'cod_departamento' => '08', 'nombre_municipio' => 'Curaren'],
            ['cod_municipio' => '0805', 'cod_departamento' => '08', 'nombre_municipio' => 'El Porvenir'],
            ['cod_municipio' => '0806', 'cod_departamento' => '08', 'nombre_municipio' => 'Guaimaca'],
            ['cod_municipio' => '0807', 'cod_departamento' => '08', 'nombre_municipio' => 'La Libertad'],
            ['cod_municipio' => '0808', 'cod_departamento' => '08', 'nombre_municipio' => 'La Venta'],
            ['cod_municipio' => '0809', 'cod_departamento' => '08', 'nombre_municipio' => 'Lepaterique'],
            ['cod_municipio' => '0810', 'cod_departamento' => '08', 'nombre_municipio' => 'Maraita'],
            ['cod_municipio' => '0811', 'cod_departamento' => '08', 'nombre_municipio' => 'Marale'],
            ['cod_municipio' => '0812', 'cod_departamento' => '08', 'nombre_municipio' => 'Nueva Armenia'],
            ['cod_municipio' => '0813', 'cod_departamento' => '08', 'nombre_municipio' => 'Ojojona'],
            ['cod_municipio' => '0814', 'cod_departamento' => '08', 'nombre_municipio' => 'Orica'],
            ['cod_municipio' => '0815', 'cod_departamento' => '08', 'nombre_municipio' => 'Reitoca'],
            ['cod_municipio' => '0816', 'cod_departamento' => '08', 'nombre_municipio' => 'Sabanagrande'],
            ['cod_municipio' => '0817', 'cod_departamento' => '08', 'nombre_municipio' => 'San Antonio de Oriente'],
            ['cod_municipio' => '0818', 'cod_departamento' => '08', 'nombre_municipio' => 'San Buenaventura'],
            ['cod_municipio' => '0819', 'cod_departamento' => '08', 'nombre_municipio' => 'San Ignacio'],
            ['cod_municipio' => '0820', 'cod_departamento' => '08', 'nombre_municipio' => 'San Juan de Flores'],
            ['cod_municipio' => '0821', 'cod_departamento' => '08', 'nombre_municipio' => 'San Miguelito'],
            ['cod_municipio' => '0822', 'cod_departamento' => '08', 'nombre_municipio' => 'Santa Ana'],
            ['cod_municipio' => '0823', 'cod_departamento' => '08', 'nombre_municipio' => 'Santa Lucia'],
            ['cod_municipio' => '0824', 'cod_departamento' => '08', 'nombre_municipio' => 'Talanga'],
            ['cod_municipio' => '0825', 'cod_departamento' => '08', 'nombre_municipio' => 'Tatumbla'],
            ['cod_municipio' => '0826', 'cod_departamento' => '08', 'nombre_municipio' => 'Valle de Angeles'],
            ['cod_municipio' => '0827', 'cod_departamento' => '08', 'nombre_municipio' => 'Villa de San Francisco'],
            ['cod_municipio' => '0828', 'cod_departamento' => '08', 'nombre_municipio' => 'Vallecillo'],
            ['cod_municipio' => '0901', 'cod_departamento' => '09', 'nombre_municipio' => 'Puerto Lempira'],
            ['cod_municipio' => '0902', 'cod_departamento' => '09', 'nombre_municipio' => 'Brus Laguna'],
            ['cod_municipio' => '0903', 'cod_departamento' => '09', 'nombre_municipio' => 'Ahuas'],
            ['cod_municipio' => '0904', 'cod_departamento' => '09', 'nombre_municipio' => 'Juan Francisco  Bulnes'],
            ['cod_municipio' => '0905', 'cod_departamento' => '09', 'nombre_municipio' => 'Ramon Villeda Morales'],
            ['cod_municipio' => '0906', 'cod_departamento' => '09', 'nombre_municipio' => 'Wampusirpi'],
            ['cod_municipio' => '1001', 'cod_departamento' => '10', 'nombre_municipio' => 'La Esperanza'],
            ['cod_municipio' => '1002', 'cod_departamento' => '10', 'nombre_municipio' => 'Camasca'],
            ['cod_municipio' => '1003', 'cod_departamento' => '10', 'nombre_municipio' => 'Colomoncagua'],
            ['cod_municipio' => '1004', 'cod_departamento' => '10', 'nombre_municipio' => 'Concepcion'],
            ['cod_municipio' => '1005', 'cod_departamento' => '10', 'nombre_municipio' => 'Dolores'],
            ['cod_municipio' => '1006', 'cod_departamento' => '10', 'nombre_municipio' => 'Intibuca'],
            ['cod_municipio' => '1007', 'cod_departamento' => '10', 'nombre_municipio' => 'Jesus de Otoro'],
            ['cod_municipio' => '1008', 'cod_departamento' => '10', 'nombre_municipio' => 'Magdalena'],
            ['cod_municipio' => '1009', 'cod_departamento' => '10', 'nombre_municipio' => 'Masaguara'],
            ['cod_municipio' => '1010', 'cod_departamento' => '10', 'nombre_municipio' => 'San Antonio'],
            ['cod_municipio' => '1011', 'cod_departamento' => '10', 'nombre_municipio' => 'San Isidro'],
            ['cod_municipio' => '1012', 'cod_departamento' => '10', 'nombre_municipio' => 'San Juan'],
            ['cod_municipio' => '1013', 'cod_departamento' => '10', 'nombre_municipio' => 'San Marcos de Sierra'],
            ['cod_municipio' => '1014', 'cod_departamento' => '10', 'nombre_municipio' => 'San Miguelito'],
            ['cod_municipio' => '1015', 'cod_departamento' => '10', 'nombre_municipio' => 'Santa Lucia'],
            ['cod_municipio' => '1016', 'cod_departamento' => '10', 'nombre_municipio' => 'Yamaranguila'],
            ['cod_municipio' => '1017', 'cod_departamento' => '10', 'nombre_municipio' => 'San Francisco de Opalaca'],
            ['cod_municipio' => '1101', 'cod_departamento' => '11', 'nombre_municipio' => 'Roatan'],
            ['cod_municipio' => '1102', 'cod_departamento' => '11', 'nombre_municipio' => 'Guanaja'],
            ['cod_municipio' => '1103', 'cod_departamento' => '11', 'nombre_municipio' => 'Jose Santos Guardiola'],
            ['cod_municipio' => '1104', 'cod_departamento' => '11', 'nombre_municipio' => 'Utila'],
            ['cod_municipio' => '1201', 'cod_departamento' => '12', 'nombre_municipio' => 'La Paz'],
            ['cod_municipio' => '1202', 'cod_departamento' => '12', 'nombre_municipio' => 'Aguanqueterique'],
            ['cod_municipio' => '1203', 'cod_departamento' => '12', 'nombre_municipio' => 'Cabanas'],
            ['cod_municipio' => '1204', 'cod_departamento' => '12', 'nombre_municipio' => 'Cane'],
            ['cod_municipio' => '1205', 'cod_departamento' => '12', 'nombre_municipio' => 'Chinacla'],
            ['cod_municipio' => '1206', 'cod_departamento' => '12', 'nombre_municipio' => 'Guajiquiro'],
            ['cod_municipio' => '1207', 'cod_departamento' => '12', 'nombre_municipio' => 'Lauterique'],
            ['cod_municipio' => '1208', 'cod_departamento' => '12', 'nombre_municipio' => 'Marcala'],
            ['cod_municipio' => '1209', 'cod_departamento' => '12', 'nombre_municipio' => 'Mercedes de Oriente'],
            ['cod_municipio' => '1210', 'cod_departamento' => '12', 'nombre_municipio' => 'Opatoro'],
            ['cod_municipio' => '1211', 'cod_departamento' => '12', 'nombre_municipio' => 'San Antonio del Norte'],
            ['cod_municipio' => '1212', 'cod_departamento' => '12', 'nombre_municipio' => 'San Jose'],
            ['cod_municipio' => '1213', 'cod_departamento' => '12', 'nombre_municipio' => 'San Juan'],
            ['cod_municipio' => '1214', 'cod_departamento' => '12', 'nombre_municipio' => 'San Pedro de Tutule'],
            ['cod_municipio' => '1215', 'cod_departamento' => '12', 'nombre_municipio' => 'Santa Ana'],
            ['cod_municipio' => '1216', 'cod_departamento' => '12', 'nombre_municipio' => 'Santa Elena'],
            ['cod_municipio' => '1217', 'cod_departamento' => '12', 'nombre_municipio' => 'Santa Maria'],
            ['cod_municipio' => '1218', 'cod_departamento' => '12', 'nombre_municipio' => 'Santiago de Puringla'],
            ['cod_municipio' => '1219', 'cod_departamento' => '12', 'nombre_municipio' => 'Yarula'],
            ['cod_municipio' => '1301', 'cod_departamento' => '13', 'nombre_municipio' => 'Gracias'],
            ['cod_municipio' => '1302', 'cod_departamento' => '13', 'nombre_municipio' => 'Belen'],
            ['cod_municipio' => '1303', 'cod_departamento' => '13', 'nombre_municipio' => 'Candelaria'],
            ['cod_municipio' => '1304', 'cod_departamento' => '13', 'nombre_municipio' => 'Cololaca'],
            ['cod_municipio' => '1305', 'cod_departamento' => '13', 'nombre_municipio' => 'Erandique'],
            ['cod_municipio' => '1306', 'cod_departamento' => '13', 'nombre_municipio' => 'Gualcince'],
            ['cod_municipio' => '1307', 'cod_departamento' => '13', 'nombre_municipio' => 'Guarita'],
            ['cod_municipio' => '1308', 'cod_departamento' => '13', 'nombre_municipio' => 'La Campa'],
            ['cod_municipio' => '1309', 'cod_departamento' => '13', 'nombre_municipio' => 'La Iguala'],
            ['cod_municipio' => '1310', 'cod_departamento' => '13', 'nombre_municipio' => 'Las Flores'],
            ['cod_municipio' => '1311', 'cod_departamento' => '13', 'nombre_municipio' => 'La Union'],
            ['cod_municipio' => '1312', 'cod_departamento' => '13', 'nombre_municipio' => 'La Virtud'],
            ['cod_municipio' => '1313', 'cod_departamento' => '13', 'nombre_municipio' => 'Lepaera'],
            ['cod_municipio' => '1314', 'cod_departamento' => '13', 'nombre_municipio' => 'Mapulaca'],
            ['cod_municipio' => '1315', 'cod_departamento' => '13', 'nombre_municipio' => 'Piraera'],
            ['cod_municipio' => '1316', 'cod_departamento' => '13', 'nombre_municipio' => 'San Andres'],
            ['cod_municipio' => '1317', 'cod_departamento' => '13', 'nombre_municipio' => 'San Francisco'],
            ['cod_municipio' => '1318', 'cod_departamento' => '13', 'nombre_municipio' => 'San Juan Guarita'],
            ['cod_municipio' => '1319', 'cod_departamento' => '13', 'nombre_municipio' => 'San Manuel Colohete'],
            ['cod_municipio' => '1320', 'cod_departamento' => '13', 'nombre_municipio' => 'San Rafael'],
            ['cod_municipio' => '1321', 'cod_departamento' => '13', 'nombre_municipio' => 'San Sebastian'],
            ['cod_municipio' => '1322', 'cod_departamento' => '13', 'nombre_municipio' => 'Santa Cruz'],
            ['cod_municipio' => '1323', 'cod_departamento' => '13', 'nombre_municipio' => 'Talgua'],
            ['cod_municipio' => '1324', 'cod_departamento' => '13', 'nombre_municipio' => 'Tambla'],
            ['cod_municipio' => '1325', 'cod_departamento' => '13', 'nombre_municipio' => 'Tomala'],
            ['cod_municipio' => '1326', 'cod_departamento' => '13', 'nombre_municipio' => 'Valladolid'],
            ['cod_municipio' => '1327', 'cod_departamento' => '13', 'nombre_municipio' => 'Virginia'],
            ['cod_municipio' => '1328', 'cod_departamento' => '13', 'nombre_municipio' => 'San Marcos de Caiquin'],
            ['cod_municipio' => '1401', 'cod_departamento' => '14', 'nombre_municipio' => 'Ocotepeque'],
            ['cod_municipio' => '1402', 'cod_departamento' => '14', 'nombre_municipio' => 'Belen Gualcho'],
            ['cod_municipio' => '1403', 'cod_departamento' => '14', 'nombre_municipio' => 'Concepcion'],
            ['cod_municipio' => '1404', 'cod_departamento' => '14', 'nombre_municipio' => 'Dolores Merendon'],
            ['cod_municipio' => '1405', 'cod_departamento' => '14', 'nombre_municipio' => 'Fraternidad'],
            ['cod_municipio' => '1406', 'cod_departamento' => '14', 'nombre_municipio' => 'La Encarnacion'],
            ['cod_municipio' => '1407', 'cod_departamento' => '14', 'nombre_municipio' => 'La Labor'],
            ['cod_municipio' => '1408', 'cod_departamento' => '14', 'nombre_municipio' => 'Lucerna'],
            ['cod_municipio' => '1409', 'cod_departamento' => '14', 'nombre_municipio' => 'Mercedes'],
            ['cod_municipio' => '1410', 'cod_departamento' => '14', 'nombre_municipio' => 'San Fernando'],
            ['cod_municipio' => '1411', 'cod_departamento' => '14', 'nombre_municipio' => 'San Francisco del Valle'],
            ['cod_municipio' => '1412', 'cod_departamento' => '14', 'nombre_municipio' => 'San Jorge'],
            ['cod_municipio' => '1413', 'cod_departamento' => '14', 'nombre_municipio' => 'San Marcos'],
            ['cod_municipio' => '1414', 'cod_departamento' => '14', 'nombre_municipio' => 'Santa Fe'],
            ['cod_municipio' => '1415', 'cod_departamento' => '14', 'nombre_municipio' => 'Sensenti'],
            ['cod_municipio' => '1416', 'cod_departamento' => '14', 'nombre_municipio' => 'Sinuapa'],
            ['cod_municipio' => '1501', 'cod_departamento' => '15', 'nombre_municipio' => 'Juticalpa'],
            ['cod_municipio' => '1502', 'cod_departamento' => '15', 'nombre_municipio' => 'Campamento'],
            ['cod_municipio' => '1503', 'cod_departamento' => '15', 'nombre_municipio' => 'Catacamas'],
            ['cod_municipio' => '1504', 'cod_departamento' => '15', 'nombre_municipio' => 'Concordia'],
            ['cod_municipio' => '1505', 'cod_departamento' => '15', 'nombre_municipio' => 'Dulce Nombre de Culmi'],
            ['cod_municipio' => '1506', 'cod_departamento' => '15', 'nombre_municipio' => 'El Rosario'],
            ['cod_municipio' => '1507', 'cod_departamento' => '15', 'nombre_municipio' => 'Esquipulas del Norte'],
            ['cod_municipio' => '1508', 'cod_departamento' => '15', 'nombre_municipio' => 'Gualaco'],
            ['cod_municipio' => '1509', 'cod_departamento' => '15', 'nombre_municipio' => 'Guarizama'],
            ['cod_municipio' => '1510', 'cod_departamento' => '15', 'nombre_municipio' => 'Guata'],
            ['cod_municipio' => '1511', 'cod_departamento' => '15', 'nombre_municipio' => 'Guayape'],
            ['cod_municipio' => '1512', 'cod_departamento' => '15', 'nombre_municipio' => 'Jano'],
            ['cod_municipio' => '1513', 'cod_departamento' => '15', 'nombre_municipio' => 'La Union'],
            ['cod_municipio' => '1514', 'cod_departamento' => '15', 'nombre_municipio' => 'Mangulile'],
            ['cod_municipio' => '1515', 'cod_departamento' => '15', 'nombre_municipio' => 'Manto'],
            ['cod_municipio' => '1516', 'cod_departamento' => '15', 'nombre_municipio' => 'Salama'],
            ['cod_municipio' => '1517', 'cod_departamento' => '15', 'nombre_municipio' => 'San Esteban'],
            ['cod_municipio' => '1518', 'cod_departamento' => '15', 'nombre_municipio' => 'San Francisco de Becerra'],
            ['cod_municipio' => '1519', 'cod_departamento' => '15', 'nombre_municipio' => 'San Francisco de La Paz'],
            ['cod_municipio' => '1520', 'cod_departamento' => '15', 'nombre_municipio' => 'Santa Maria del Real'],
            ['cod_municipio' => '1521', 'cod_departamento' => '15', 'nombre_municipio' => 'Silca'],
            ['cod_municipio' => '1522', 'cod_departamento' => '15', 'nombre_municipio' => 'Yocon'],
            ['cod_municipio' => '1523', 'cod_departamento' => '15', 'nombre_municipio' => 'Patuca'],
            ['cod_municipio' => '1601', 'cod_departamento' => '16', 'nombre_municipio' => 'Santa Barbara'],
            ['cod_municipio' => '1602', 'cod_departamento' => '16', 'nombre_municipio' => 'Arada'],
            ['cod_municipio' => '1603', 'cod_departamento' => '16', 'nombre_municipio' => 'Atima'],
            ['cod_municipio' => '1604', 'cod_departamento' => '16', 'nombre_municipio' => 'Azacualpa'],
            ['cod_municipio' => '1605', 'cod_departamento' => '16', 'nombre_municipio' => 'Ceguaca'],
            ['cod_municipio' => '1606', 'cod_departamento' => '16', 'nombre_municipio' => 'Concepcion del Norte'],
            ['cod_municipio' => '1607', 'cod_departamento' => '16', 'nombre_municipio' => 'Concepcion del Sur'],
            ['cod_municipio' => '1608', 'cod_departamento' => '16', 'nombre_municipio' => 'Chinda'],
            ['cod_municipio' => '1609', 'cod_departamento' => '16', 'nombre_municipio' => 'El Nispero'],
            ['cod_municipio' => '1610', 'cod_departamento' => '16', 'nombre_municipio' => 'Gualala'],
            ['cod_municipio' => '1611', 'cod_departamento' => '16', 'nombre_municipio' => 'Ilama'],
            ['cod_municipio' => '1612', 'cod_departamento' => '16', 'nombre_municipio' => 'Macuelizo'],
            ['cod_municipio' => '1613', 'cod_departamento' => '16', 'nombre_municipio' => 'Naranjito'],
            ['cod_municipio' => '1614', 'cod_departamento' => '16', 'nombre_municipio' => 'Nuevo Celilac'],
            ['cod_municipio' => '1615', 'cod_departamento' => '16', 'nombre_municipio' => 'Petoa'],
            ['cod_municipio' => '1616', 'cod_departamento' => '16', 'nombre_municipio' => 'Proteccion'],
            ['cod_municipio' => '1617', 'cod_departamento' => '16', 'nombre_municipio' => 'Quimistan'],
            ['cod_municipio' => '1618', 'cod_departamento' => '16', 'nombre_municipio' => 'San Francisco de Ojuera'],
            ['cod_municipio' => '1619', 'cod_departamento' => '16', 'nombre_municipio' => 'San Jose de Colinas'],
            ['cod_municipio' => '1620', 'cod_departamento' => '16', 'nombre_municipio' => 'San Luis'],
            ['cod_municipio' => '1621', 'cod_departamento' => '16', 'nombre_municipio' => 'San Marcos'],
            ['cod_municipio' => '1622', 'cod_departamento' => '16', 'nombre_municipio' => 'San Nicolas'],
            ['cod_municipio' => '1623', 'cod_departamento' => '16', 'nombre_municipio' => 'San Pedro Zacapa'],
            ['cod_municipio' => '1624', 'cod_departamento' => '16', 'nombre_municipio' => 'San Vicente Centenario'],
            ['cod_municipio' => '1625', 'cod_departamento' => '16', 'nombre_municipio' => 'Santa Rita'],
            ['cod_municipio' => '1626', 'cod_departamento' => '16', 'nombre_municipio' => 'Trinidad'],
            ['cod_municipio' => '1627', 'cod_departamento' => '16', 'nombre_municipio' => 'Las Vegas'],
            ['cod_municipio' => '1628', 'cod_departamento' => '16', 'nombre_municipio' => 'Nueva Frontera'],
            ['cod_municipio' => '1701', 'cod_departamento' => '17', 'nombre_municipio' => 'Nacaome'],
            ['cod_municipio' => '1702', 'cod_departamento' => '17', 'nombre_municipio' => 'Alianza'],
            ['cod_municipio' => '1703', 'cod_departamento' => '17', 'nombre_municipio' => 'Amapala'],
            ['cod_municipio' => '1704', 'cod_departamento' => '17', 'nombre_municipio' => 'Aramecina'],
            ['cod_municipio' => '1705', 'cod_departamento' => '17', 'nombre_municipio' => 'Caridad'],
            ['cod_municipio' => '1706', 'cod_departamento' => '17', 'nombre_municipio' => 'Goascoran'],
            ['cod_municipio' => '1707', 'cod_departamento' => '17', 'nombre_municipio' => 'Langue'],
            ['cod_municipio' => '1708', 'cod_departamento' => '17', 'nombre_municipio' => 'San Francisco de Coray'],
            ['cod_municipio' => '1709', 'cod_departamento' => '17', 'nombre_municipio' => 'San Lorenzo'],
            ['cod_municipio' => '1801', 'cod_departamento' => '18', 'nombre_municipio' => 'Yoro'],
            ['cod_municipio' => '1802', 'cod_departamento' => '18', 'nombre_municipio' => 'Arenal'],
            ['cod_municipio' => '1803', 'cod_departamento' => '18', 'nombre_municipio' => 'El Negrito'],
            ['cod_municipio' => '1804', 'cod_departamento' => '18', 'nombre_municipio' => 'El Progreso'],
            ['cod_municipio' => '1805', 'cod_departamento' => '18', 'nombre_municipio' => 'Jocon'],
            ['cod_municipio' => '1806', 'cod_departamento' => '18', 'nombre_municipio' => 'Morazan'],
            ['cod_municipio' => '1807', 'cod_departamento' => '18', 'nombre_municipio' => 'Olanchito'],
            ['cod_municipio' => '1808', 'cod_departamento' => '18', 'nombre_municipio' => 'Santa Rita'],
            ['cod_municipio' => '1809', 'cod_departamento' => '18', 'nombre_municipio' => 'Sulaco'],
            ['cod_municipio' => '1810', 'cod_departamento' => '18', 'nombre_municipio' => 'Victoria'],
            ['cod_municipio' => '1811', 'cod_departamento' => '18', 'nombre_municipio' => 'Yorito'],
        ]);
    }
}
